feat(cache): use new resource implementation
gravitee-io/gravitee-policy-cache pull request #21
Opened 2021-02-16 16:34 UTC by gcusnieux

fix: gravitee-io/issues#599

2021-02-26 13:59 UTC, ytvnr requested changes

2021-02-26 13:59 UTC, ytvnr commented on pom.xml
> +        <gravitee-gateway.version>3.5.4</gravitee-gateway.version>
why not 3.7.0-SNAPSHOT ?

2021-02-26 13:59 UTC, ytvnr commented on src/main/java/io/gravitee/policy/cache/CacheResponse.java
> +import java.io.Serializable;
you can delete this useless import

2021-02-26 13:59 UTC, ytvnr commented on src/main/java/io/gravitee/policy/cache/mapper/CacheResponseMapper.java
> +        public Buffer deserialize(JsonParser p, DeserializationContext ctxt) throws IOException, JsonProcessingException {
```suggestion
        public Buffer deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
```

2021-02-26 13:59 UTC, ytvnr commented on src/main/java/io/gravitee/policy/cache/resource/CacheElement.java
>      private int timeToLive = 0;
why not have a long here ? it could avoid a cast in CachePolicy.
wdyt ?

2021-03-05 14:12 UTC, phiz71 approved these changes

2021-03-05 14:49 UTC, merged