Issues/6980 enhance.cache.policy
gravitee-io/gravitee-policy-cache pull request #42
Opened 2022-01-31 13:17 UTC by NicolasGeraud

**Issue**

https://github.com/gravitee-io/issues/issues/6980

**Description**
Choose the method to cache and add a response condition

2022-02-02 16:00 UTC, ytvnr commented on src/test/java/io/gravitee/policy/cache/CachePolicyTest.java
> +    }
can we have tests with condition (passing, failing, erroring) ?

2022-02-02 16:02 UTC, marcambier requested changes

2022-02-03 08:56 UTC, NicolasGeraud commented on src/main/java/io/gravitee/policy/cache/proxy/EvaluableProxyResponse.java
> +    public HttpHeaders getHeaders() {
👍

2022-02-03 08:56 UTC, NicolasGeraud commented on src/main/java/io/gravitee/policy/cache/proxy/EvaluableProxyResponse.java
> +    public int getStatus() {
👍

2022-02-03 15:23 UTC, NicolasGeraud commented on src/main/java/io/gravitee/policy/cache/CachePolicy.java
> +            Boolean value = context.getTemplateEngine().getValue(condition, Boolean.class);
you're right

2022-02-03 15:24 UTC, NicolasGeraud commented on src/main/java/io/gravitee/policy/cache/CachePolicy.java
> +            //context.setAttribute("proxyResponse", proxyResponse);
👍

2022-02-03 15:25 UTC, NicolasGeraud commented on src/main/java/io/gravitee/policy/cache/CachePolicy.java
> +            context.getTemplateEngine().getTemplateContext().setVariable(UPSTREAM_RESPONSE, new EvaluableProxyResponse(proxyResponse));
I think this PR will only be focus on headers, I create another issue to support content

2022-02-05 09:41 UTC, NicolasGeraud commented on src/test/java/io/gravitee/policy/cache/CachePolicyTest.java
> +    public void shouldFailIfNoCache() {
👍

2022-02-05 09:41 UTC, NicolasGeraud commented on src/main/java/io/gravitee/policy/cache/proxy/EvaluableProxyResponse.java
> +        super(null);
I do not support content in this PR

2022-02-07 20:50 UTC, NicolasGeraud commented
Ok i fix this

2022-02-08 13:33 UTC, marcambier approved these changes

2022-02-08 13:34 UTC, merged

2022-02-08 13:52 UTC, graviteeio commented
:tada: This PR is included in version 1.9.1 :tada:

The release is available on:
- `1.9.1`
- [GitHub release](https://github.com/gravitee-io/gravitee-policy-cache/releases/tag/1.9.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: